name: Telosa Java Dev CI

on:
  pull_request_review:
    types: [ submitted ]
  push:
    branches: [ main, github-actions ]

jobs:
  build-and-test:
    if: (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build, and test only
        run: ./mvnw -B test --file pom.xml

  build:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]') && !github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build only
        run: ./mvnw -B compile --file pom.xml

